#!/bin/sh -e

show_usage(){
  (
    echo "Usage: $0 [options...] <customer_id>"
    echo
    echo "Options:"
    echo "   -h, --help                 show this help"
    echo
  ) 1>&2
  exit 1
}

parse_option_error_exit() {
    echo "ERROR: $1 requires a non-empty option argument." 1>&2
    exit 1
}

if ! type curl >/dev/null 2>&1; then
  echo "ERROR: curl command not found." 1>&2
  exit 1
fi

load_env_dir="$(dirname "$(realpath "$0")")"
load_env() {
    load_env_dir="$1"

    if [ -f "$load_env_dir/.env" ]; then
        . "$load_env_dir/.env"
        return
    fi

    load_env "$(dirname "$load_env_dir")"
}
load_env "$load_env_dir"

# show Usage with h and help
case "${1:-""}" in -h | --help) show_usage ;; esac

customer_id=${1:-$FINCODE_CUSTOMER_ID}

curl \
  -H "Content-Type: application/json;charset=UTF-8" \
  -H "Authorization: Bearer ${FINCODE_API_SECRET_KEY}" \
  "${FINCODE_API_URL}"/customers/"${customer_id}"/cards
