#!/bin/sh -e

show_usage(){
  (
    echo "Usage: $0 [options...]"
    echo
    echo "Options:"
    echo "   -h, --help                 show this help"
    echo "       --pay_type             Card"
    echo
  ) 1>&2
  exit 1
}

parse_option_error_exit() {
    echo "ERROR: $1 requires a non-empty option argument." 1>&2
    exit 1
}

if ! type curl >/dev/null 2>&1; then
  echo "ERROR: curl command not found." 1>&2
  exit 1
fi

load_env_dir="$(dirname "$(realpath "$0")")"
load_env() {
    load_env_dir="$1"

    if [ -f "$load_env_dir/.env" ]; then
        . "$load_env_dir/.env"
        return
    fi

    load_env "$(dirname "$load_env_dir")"
}
load_env "$load_env_dir"

pay_type="${DEFAULT_PAY_TYPE}"

while :; do
    case $1 in
        -h|-\?|--help) show_usage   ;;
        --pay_type)
            if [ -n "$2" ]; then
                pay_type=$2; shift
            else
              parse_option_error_exit "$1"
            fi
            ;;
        --) shift; break ;;
        -?*) echo "WARN: Unknown option (ignored): $1" 1>&2 ;;
        *) break ;;
    esac

    shift
done

curl \
  -H "Content-Type: application/json;charset=UTF-8" \
  -H "Authorization: Bearer ${FINCODE_API_SECRET_KEY}" \
  "${FINCODE_API_URL}"/payments?pay_type="${pay_type}" \
